
; MSX BIOS

RDSLT  equ  000Ch
WRSLT  equ  0014h
ENASLT equ  0024h
IDBYT2 equ  002Dh
IDBYT3 equ  002Eh
CALLF  equ  0030h

; MSX WORK

USRTAB equ 0F39Ah
TXTTAB equ 0F676h
NEWKEY equ 0FBE5h
BOTTOM equ 0FC48h
HIMEM  equ 0FC4Ah
EXPTBL equ 0FCC1h
SLTTBL equ 0FCC5h
SLTWRK equ 0FD09h
H.TIMI equ 0FD9Fh
H.INIP equ 0FDC7h
H.STKE equ 0FEDAh
H.MDTM equ 0FF93h
H.PHYD equ 0FFA7h

; MSX memory mapped I/O

SSLOT  equ 0FFFFh

; MSX I/O

PSLOT  equ 0A8h
P0_REG equ 0FCh
P1_REG equ 0FDh
P2_REG equ 0FEh
P3_REG equ 0FFh

