
; NEXTOR

CHGBNK equ 7FD0h

	org	76E0h - (OFFSET_TABLE.top - OFFSET_TABLE)

OFFSET_TABLE:

	dw	BANK4_SEGMENT - .top

	dw	BANK0_INIT2_PATCH - .top
	dw	BANK4_INIT2_ADDRESS - .top

	dw	BANK0_CLEAN_PATCH - .top
	dw	BANK4_CLEAN_ADDRESS - .top

	dw	BANK0_HIMEM_PATCH - .top
	dw	BANK4_HIMEM_ADDRESS - .top
.top:

BANK0_INIT2_PATCH:
BANK4_INIT2_ADDRESS equ $+1
	ld	hl, 0
	jr	NEXTOR_BANK4_JUMPHL

BANK0_CLEAN_PATCH:
BANK4_CLEAN_ADDRESS equ $+1
	ld	hl, 0
	jr	NEXTOR_BANK4_JUMPHL

BANK0_HIMEM_PATCH:
BANK4_HIMEM_ADDRESS equ $+1
	ld	hl, 0

NEXTOR_BANK4_JUMPHL:
	push	hl

BANK4_SEGMENT equ $+1
	ld	a, 4
	jp	CHGBNK
